apiVersion: v1
kind: Service
metadata:
  name: karvaan-music
  namespace: r16a-cloud
spec:
  type: ClusterIP
  selector:
    app: karvaan-music
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
